{% set name = "FileSeeker" %}
{% set version = "0.0.1" %}
{% set url = "https://pypi.io/packages/source/" + name[0] + "/" + name + "/" + name + "-" + version + ".tar.gz" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  fn: "{{ name }}-{{ version }}.tar.gz"
  url: "{{ url }}"
  sha256: febe8796484b5d629d1fbf36d53c3e60888cf6d0451b49b18bfccb5e3735eaf7

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - matplotlib
    - numpy>=1.21.5
    - pip
    - python
  run:
    - matplotlib
    - numpy>=1.21.5
    - python

test:
  imports:
    - FileSeeker

about:
  home: "https://github.com/neutrinomuon/FileSeeker"
  license_file: 'LICENSE.txt'
  license_url: "https://github.com/neutrinomuon/FileSeeker/LICENSE.txt"
  summary: "Search for a given file in a directory using Python"
  doc_url: "https://github.com/neutrinomuon/FileSeeker"
  dev_url: "https://github.com/neutrinomuon/FileSeeker"

extra:
  recipe-maintainers:
    - neutrinomuon